### ISSUE TITLE
Add missing CBOR data types and Go data types.  Use new Go struct tags "toarray" and "keyasint".

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor-fuzz#10]
Signed CWT struct example uses both "keyasint" and "toarray" so it might be a good starting point for cbor-fuzz.

Add any other missing data types to the struct.

Also make sure all data types in CBOR and Go are represented outside of the struct as well.

Example struct from encoding/gob fuzz:
```
type X struct {
	A int
	B string
	C float64
	D []byte
	E interface{}
	F complex128
	G []interface{}
	H *int
	I **int
	J *X
	K map[string]int
}
```

**Comment by fxamacker** [comment]
Closed by commit 75e3637ee728ed6d9146855682678881d7543365 and e8a506103d077a66d6a9eb7a4c59a7195dd0cb7e.
