### ISSUE TITLE
Plans to open source the new fuzzer?

### ISSUE THREAD

**Issue by adwsingh** [fxamacker/cbor-fuzz#14]
I saw that recently the README.MD was updated to indicate that this library is no more used and instead a private fuzzer which is more robust has replaced it.

I am working on a similar project but for Java, and was wondering if you would open source your new fuzzer so it can help other people like me to fuzz other CBOR implementations.

**Comment by fxamacker** [comment]
Hi @adwsingh, it would take more time than I currently have to open source the newer fuzzer, but I think a Java/Kotlin/Scala fuzzing project can be more helpful to you. It doesn't have to be CBOR related.

- For initial corpus, you can use CBOR data examples from [Appendix A of RFC 8949](https://www.rfc-editor.org/rfc/rfc8949.html#name-examples-of-encoded-cbor-da), other RFCs, etc.

- Find a good quality Java project for any binary data format that uses same fuzzer that you want to use (e.g. [Jazzer](https://github.com/CodeIntelligenceTesting/jazzer)).  Similarity of API can save time if you are new to fuzzing.  Another option is to find [libfuzzer](https://llvm.org/docs/LibFuzzer.html) examples in C++.

- Give enough time for fuzzer to find problems.  E.g. [fxamacker/cbor](https://github.com/fxamacker/cbor) v2.5.0 was fuzzed 5+ billion execs in the last run of fuzzing but total runs for v2.5.0-beta to v2.5.0 release finished over 20+ billion execs.

Best of luck fuzzing codecs in JVM!
