### ISSUE TITLE
Add 320 fuzzing-generated files to corpus

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor-fuzz#3]
The corpus folder contains 80 manually-created files.  

So it can take hours of fuzzing for **cover counter** to stop growing with just these 80 as a starting point.  

The corpus counter still increases, but cover seems to stop after about 300 generated files -- so that's a nicer starting point for new users of your CBOR library.

If you want, I can submit a pull request with the first 320 files generated by fuzzing with latest cbor and cbor-fuzz.

**Comment by fxamacker** [comment]
Sounds good.  You can send more files (up to 500) if you have them.

**Comment by fxamacker** [comment]
Merged pull request #4 to add 337 corpus files generated by fuzzing around 38 hours.
