### ISSUE TITLE
Add 17 files from COSE examples -- RFC 8152 Appendix B and C.

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor-fuzz#9]
For convenience, there are 17 files in JSON format at:
https://github.com/cose-wg/Examples/tree/master/RFC8152

Extracting the hex values from these files should be quick compared to working directly from the RFC document.

**Comment by fxamacker** [comment]
Commit 78b23645ecea04b0123b84ed49071419d0eaa31b closes this issue.

@x448 Please fuzz again if you have time and send new corpus files if the cover count increases.

**Comment by x448** [comment]
@fxamacker Fuzzing started with cbor v1.2.0 and cbor-fuzz (commit 009e9b3e4bd3e0159e8bca1abafcaa6ec5d4e4e7) -- I'll leave it running and let you know how it goes.  I'm using clean corpus folder with just the 441 initial files.
